### ISSUE TITLE
Assertions statusCodeIsNotXXX() not working 

### ISSUE THREAD

**Issue by ValeriusSchmidt** [Qytera-Gmbh/QTAF#255] opened 2024-02-06 10:49 UTC
```java
@Test
public void test3() {
  String body1 = "{\"name\": \"morpheus\",\"job\": \"leader\"}";
  apiTest(
    this,
    List.of(
      baseUri("https://reqres.in"),
      body(body1)
    ),
    postRequest("/api/users"),
    List.of(statusCodeIsNot3xx()) 
  );
}
```

When trying to run a test with a statusCodeIsNotXXX() Assertion the test will always fail. The Report shows the following entries: 

```json
"assertions": [
  {
    "type": "ASSERT_EQUALS",
    "condition": false,
    "actual": "UNKNOWN_ACTUAL_VALUE_forStatusCodeAssertion", 
    "expected": "not 3xx",
    "status": "UNDEFINED", 
    "uuid": "e804d2ba-0c30-4802-ac20-8117f3714bdf",
    "assertions": [],
    "level": "INFO",
    "message": "statusCodeIsNot3xx assertion",
    "featureId": "",
    "abstractScenarioId": "",
    "scenarioId": ""
  }
],
```

**Comment by OliverHoenig** [comment] 2024-02-14 13:44
Thank you for reporting these issue. I will try to reproduce the error and investigate why this behaviour occurs.

**Comment by OliverHoenig** [comment] 2024-02-14 13:59
I could not reproduce the error. 
As the API testing feature is currently being prepared for release, intensive work has been done on it over the last few days. It is likely that the bug has already been fixed. 
If in your opinion the current version still creates an unexpected LogMessage, please report this in a new issue.
I will now close this issue.
Thanks for your help

**Closed by OliverHoenig** 2024-02-14 13:59 UTC
Labels: 📄 bug, ↗️ high priority, 🚦 under investigation
