### ISSUE TITLE
Console summary doesn't recognize a failed API test

### ISSUE THREAD

**Issue by MoritzSalein** [Qytera-Gmbh/QTAF#265] opened 2024-03-05 14:55 UTC
After a API test case where I get a failure in the execution, the console test summary (from TestNG?) is wrong. I only see the error when I execute it in the terminal with maven, e.g. `mvn test -Dtest=testclass`

Output (Line 4 is the test with failure, in the summary seems all tests run):

`15:54:04.931 [main] INFO  de.qytera.qtaf.core - [Test] [74633460] [testapi] started
15:54:06.471 [main] INFO  de.qytera.qtaf.core - [Test] [74633460] [testapi] success
15:54:06.472 [main] INFO  de.qytera.qtaf.core - [Test] [1015539793] [testapi] started
15:54:06.815 [main] INFO  de.qytera.qtaf.core - [Test] [1015539793] [testapi] failure
15:54:06.833 [main] INFO  de.qytera.qtaf.core - [QTAF] - testing finished
[main] INFO org.reflections.Reflections - Reflections took 24 ms to scan 4 urls, producing 43 keys and 112 values
[main] INFO org.reflections.Reflections - Reflections took 1 ms to scan 0 urls, producing 0 keys and 0 values
[main] INFO org.reflections.Reflections - Reflections took 19 ms to scan 4 urls, producing 43 keys and 112 values
[main] INFO org.reflections.Reflections - Reflections took 0 ms to scan 0 urls, producing 0 keys and 0 values
15:54:07.975 [main] INFO  de.qytera.qtaf.core - [QTAF] Log files persisted
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.175 s -- in testapi
[INFO] 
[INFO] Results:
[INFO]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.936 s
[INFO] Finished at: 2024-03-05T15:54:08+01:00
[INFO] ------------------------------------------------------------------------
`

**Comment by OliverHoenig** [comment] 2024-03-12 13:36
Hello Moritz, thank you very much for reporting.

- Was the test case generally marked as passed or is only the summary in the console incorrect?
- Was a correct LogMessage created? More specifically: When this test case is executed, is a LogMessage created indicating that the test case failed and which assertion led to the error?

Thanks for your help.

**Comment by OliverHoenig** [comment] 2024-04-02 12:47
The feature was still in the design phase. The approach followed there for API testing will not be pursued further. A different approach to implementing API tests using QTAF is being considered. 
As this issue relates to the old approach, which is now no longer being pursued, the issue is closed.

**Closed by OliverHoenig** 2024-04-02 12:47 UTC
Labels: 📄 bug, ➕ information required, 🚦 under investigation, 🛠rest assured
